Remove linux/arm/v7 builds
docker.io no longer ships fol platform
    [linux/arm/v7 internal] load metadata for docker.io/library/node:latest
    ERROR: no match for platform in manifest: not found